version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - '5400:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build: ./server
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db
    x-develop:
      watch:
        - action: rebuild
          path: ./server
          target: /app

volumes:
  db:
    driver: local

networks:
  default:
    name: go-network
