version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: $(POSTGRES_DB)
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build: ./server
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  default:
    name: go-network
