version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - '5400:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build: ./server
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-.env.example}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:-.env.example}
      POSTGRES_URL: db
      POSTGRES_PORT: 5432
    ports:
      - '80:8000'
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  default:
    name: go-network
